dist: trusty
language: cpp

matrix:
  include:
    - os: linux
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - eval "${MATRIX_EVAL}"
  - pip install --user cpp-coveralls

script:
  - mkdir build
  - cd build
  - cmake -DCOVERAGE=1 ../libft0cc
  - cmake --build . -- -j4
  - GTEST_COLOR=1 ctest -V

after_success:
  - coveralls --root . -E ".*gtest.*" -E ".*CMakeFiles.*" --gcov gcov-7

notifications:
  email:
    on_success: change
    on_failure: change
