dist: trusty
sudo: required
language: cpp

matrix:
  include:
    - os: linux
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - USE_GCC=1
      after_success:
        - coveralls --gcov gcov-7 --root .. --include src --include include

before_install:
  - |
    if [ "$USE_GCC" = "1" ]; then
      export CC=gcc-7 CXX=g++-7
    else
      sudo CXX="$CXX" CC="$CC"
      sudo ./travis/install_libcxx.sh -v 5.0.0
    fi
  - sudo pip install cpp-coveralls

script:
  - cd libft0cc
  - mkdir build
  - cd build
  - cmake -DCOVERAGE=$USE_GCC ..
  - cmake --build . -- -j4
  - GTEST_COLOR=1 ctest -V

notifications:
  email:
    on_success: change
    on_failure: change
