dist: trusty
sudo: false
language: cpp

matrix:
  include:
#  - os: linux
#    env:
#    - MATRIX_EVAL="CC=clang && CXX=clang++"
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && GCOV=gcov-7"

before_script:
- npm install -g eclint
- eclint check "*"

before_install:
- eval "${MATRIX_EVAL}"

script:
- cd libft0cc
- mkdir build
- cd build
- cmake -DCOVERAGE=1 -DCMAKE_BUILD_TYPE=Debug ..
- cmake --build . -- -j4
- cmake --build . --target coveralls

notifications:
  email:
    on_success: change
    on_failure: change
