dist: trusty
sudo: false
language: cpp

matrix:
  include:
#    - os: linux
#      env:
#        - MATRIX_EVAL="CC=clang && CXX=clang++"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      after_success:
        - coveralls --gcov gcov-7 --root .. --include src --include include

before_install:
  - eval "${MATRIX_EVAL}"
  - pip install --user cpp-coveralls

script:
  - cd libft0cc
  - mkdir build
  - cd build
  - cmake -DCOVERAGE=1 ..
  - cmake --build . -- -j4
  - GTEST_COLOR=1 ctest -V

notifications:
  email:
    on_success: change
    on_failure: change
