dist: trusty
sudo: false
language: cpp

matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-6.0
        packages:
        - clang-6.0
    env:
    - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
    - COVERALLS_ENABLE=0
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && GCOV=gcov-7"
    - COVERALLS_ENABLE=1

before_script:
- npm install -g eclint
- eclint check "*"

before_install:
- eval "${MATRIX_EVAL}"

script:
- cd libft0cc
- mkdir build
- cd build
- cmake -DCOVERAGE=${COVERALLS_ENABLE} -DCMAKE_BUILD_TYPE=Debug ..
- cmake --build . -- -j4
- |
  if [ $COVERALLS_ENABLE -eq 1 ]
  then
    cmake --build . --target coveralls
  fi

notifications:
  email:
    on_success: change
    on_failure: change
